configfile: "config.yaml"

MODELS = config["MODELS"]

rule run:
    input:
        expand("nni/experiment_results/{model}.csv", 
                model = MODELS)

rule generate_nni_experiment_and_search_space_files:
    output:
        experiment   = expand("nni/{model}_experiments.yaml", 
                                model = MODELS),
                                
        search_space = expand("nni/Search_space/{model}_search_space.json",
                                model = MODELS),        
    conda:
        "Envs/example.yaml"      
    script:
        "Scripts/generate_nni_experiments_and_search_spaces.py"
                
rule hyperparam_opt:
    input:
        experiment = expand("nni/{model}_experiments.yaml", 
                             model = MODELS),
    output:
        result_csv = expand("nni/experiment_results/{model}.csv", 
                             model = MODELS)
    conda:
        "Envs/example.yaml"
    params:
        port = {config["NNI_PORT"]}
    script:
        "Scripts/start_nni_experiments.py"